In [1]:
import sys

print(sys.executable)

c:\Users\kaila\OneDrive\Desktop\Amazon ML\.venv\Scripts\python.exe

In [4]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [ ]:
train_dir = "../dataset/train"

source1 = pd.read_csv(os.path.join(train_dir, "train_source1.tsv"),sep="\t")
source2 = pd.read_csv(os.path.join(train_dir, "train_source2.tsv"),sep="\t")
source3 = pd.read_csv(os.path.join(train_dir, "train_source3.tsv"),sep="\t")
ground_truth = pd.read_csv(os.path.join(train_dir, "train_ground_truth.tsv"),sep="\t")

In [79]:
print(source1.shape)
print(source2.shape)
print(source3.shape)
print(ground_truth.shape)
print(source1.columns)

ground_truth.head()

(2206821, 4)
(5034616, 4)
(5285603, 4)
(2206821, 2)
Index(['entity_id', 'business_name', 'business_address', 'country'], dtype='str')

  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...

In [80]:
source1.head()

,entity_id,business_name,business_address,country
0,S1-925783039,Orelee's Barbershop,"1795 Westchester Drive, High Point, NC",US
1,S1-773889195,Prime Money,"17560 Ellis Road, Tahlequah, OK",US
2,S1-377745466,B+ Retail Inc,"1712 Montebello Avenue, Phoenix, AZ",US
3,S1-133037285,Christ Chapel,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",US
4,S1-755362802,Prabhav Business Center,"797, Lake Town Block A, Kolkata, Howrah, West ...",India

In [81]:
source2.head()

,entity_id,business_name,business_address,country
0,S2-166376419,राम मार्केटिंग प्राइवेट लिमिटेड,"KH NO. -570/13, NEW DELHI, WEST DELHI, Delhi",India
1,S2-764573417,-- Holloway Peak Inc Seafood,"105 ELM ST, MORGANTON, NC",US
2,S2-639257739,आदित्य प्रॉपर्टीज एलएलपी,"G-3/571, GULMOHAR COLONY, BHOPAL, Madhya Pradesh",India
3,S2-163963287,Summit Inc,"GREENSBORO, NC, 19 1/2 STARDUST TRAIL",US
4,S2-49942811,Delta Tetlecommunication Inc,"914 PIERPONT AVE, CLEVELAND, OH",US

In [82]:
print(source1.dtypes)
print()
print(source2.dtypes)
print()
print(source3.dtypes)
print()
print(ground_truth.dtypes)

entity_id           str
business_name       str
business_address    str
country             str
dtype: object

entity_id           str
business_name       str
business_address    str
country             str
dtype: object

entity_id           str
business_name       str
business_address    str
country             str
dtype: object

source1_entity_id     str
matched_entity_ids    str
dtype: object

In [83]:
#Handling missing values check in each
print("Source 1\n")
print(source1.isna().sum())

print("Source 2\n")
print(source2.isna().sum())

print("Source 3 \n")
print(source3.isna().sum())

print("Ground Truth\n")
print(ground_truth.isna().sum())

Source 1

entity_id           0
business_name       0
business_address    0
country             0
dtype: int64
Source 2

entity_id                0
business_name            2
business_address    168967
country                  0
dtype: int64
Source 3

entity_id                0
business_name           13
business_address    175916
country                  0
dtype: int64
Ground Truth

source1_entity_id          0
matched_entity_ids    123247
dtype: int64

In [84]:
#Missing vales dekh lo kesi and why missing and possinle reasons 
ground_truth[ground_truth["matched_entity_ids"].isna()].head(10)

    source1_entity_id matched_entity_ids
21       S1-302869473                NaN
37       S1-262997549                NaN
40       S1-508022910                NaN
51       S1-666499407                NaN
64       S1-965524997                NaN
74       S1-830177070                NaN
114      S1-202262115                NaN
129      S1-625699510                NaN
131      S1-604865181                NaN
170       S1-88224713                NaN

Ok for these it is NaN means no matching id in S2 and S3

In [85]:
source2[source2["business_address"].isna()].head(10)

,entity_id,business_name,business_address,country
53,S2-187379771,"Guerra And Krueger Table, LLC",NaN,US
69,S2-751730544,L E Pierce Cal [PC],NaN,US
93,S2-162849450,Preferred Bay Montage Inc,NaN,US
195,S2-616836723,DELONG STRATEGIC READY,NaN,US
236,S2-39617527,Desert Vanguard ([Maintenance]),NaN,US
346,S2-582984116,Wildlife Sóciety,NaN,US
352,S2-762023797,Orellana Kensington,NaN,US
376,S2-682660453,rathi holdings,NaN,India
390,S2-752363850,Berry Saul,NaN,US
424,S2-14102665,"Thrasher, Wanner 5tenson LLC Center",NaN,US

Ok for Sources Nan means no adresses given by the Business entity means we cannot invent our own adress using imputation and all other tecniques 

Means our goal will be to make classfier even when we dont have adress and make classfication on basis of other columns

In [86]:
print(source1["country"].value_counts())

country
US       1323633
India     883188
Name: count, dtype: int64

In [87]:
print("\nSource 2:")
print(source2["country"].value_counts())

Source 2:
country
US       3016817
India    2017799
Name: count, dtype: int64

In [88]:
print("\nSource 3:")
print(source3["country"].value_counts())

Source 3:
country
US       3170056
India    2115547
Name: count, dtype: int64

Ok we don't One Hot Encode it right now according to the proboem statement

In [89]:
ground_truth[ground_truth["matched_entity_ids"].notna()]["matched_entity_ids"].head()
#Ok so they are comma separted not in any json or data structre as the dtypes tell

0    S2-681193310,S2-743505751,S3-775321672,S3-1129...
1    S2-249013014,S2-197070651,S3-478195123,S3-3843...
2               S2-790675320,S2-479876582,S3-878454467
3                S2-153058913,S2-24659151,S3-679606215
4    S2-478959098,S2-553508714,S2-625774905,S3-7280...
Name: matched_entity_ids, dtype: str

In [90]:
match_counts = (ground_truth["matched_entity_ids"].fillna("").apply(lambda x: 0 if x == "" else len(x.split(","))))
match_counts

0          5
1          4
2          3
3          3
4          6
          ..
2206816    1
2206817    4
2206818    6
2206819    3
2206820    2
Name: matched_entity_ids, Length: 2206821, dtype: int64

In [91]:
print(match_counts.value_counts())

matched_entity_ids
3     530841
4     484115
2     375212
5     321957
6     164868
0     123247
1     119157
7      63968
8      18680
9       4205
10       534
11        37
Name: count, dtype: int64

In [92]:
print(match_counts.value_counts().sort_index()) 
#How many at max matches can we have

matched_entity_ids
0     123247
1     119157
2     375212
3     530841
4     484115
5     321957
6     164868
7      63968
8      18680
9       4205
10       534
11        37
Name: count, dtype: int64

In [93]:
#Now investiagte what makes a pair look like match 
positive_examples = (ground_truth[ground_truth["matched_entity_ids"].notna()].head(10))

positive_examples #get the exmaples for S1 and there correspofing matching ids

  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...
5       S1-18727616  S2-755677256,S3-187831601,S3-641489370,S3-4762...
6      S1-318373630                          S2-660036492,S3-804600254
7       S1-86989137                          S3-274817120,S3-312496301
8       S1-29845983                          S2-648035184,S3-588502663
9      S1-789009573              S2-383871912,S3-74481402,S3-576451439

In [94]:
matched_ids = positive_examples["matched_entity_ids"]
matched_ids

0    S2-681193310,S2-743505751,S3-775321672,S3-1129...
1    S2-249013014,S2-197070651,S3-478195123,S3-3843...
2               S2-790675320,S2-479876582,S3-878454467
3                S2-153058913,S2-24659151,S3-679606215
4    S2-478959098,S2-553508714,S2-625774905,S3-7280...
5    S2-755677256,S3-187831601,S3-641489370,S3-4762...
6                            S2-660036492,S3-804600254
7                            S3-274817120,S3-312496301
8                            S2-648035184,S3-588502663
9                S2-383871912,S3-74481402,S3-576451439
Name: matched_entity_ids, dtype: str

In [95]:
all_matched_ids = []

for value in matched_ids:
    ids = value.split(",")

    for entity_id in ids:
        all_matched_ids.append(entity_id)

In [96]:
print(all_matched_ids)
len(all_matched_ids) #get all macthed id and then split in s2 and s3

['S2-681193310', 'S2-743505751', 'S3-775321672', 'S3-11291185', 'S3-860443364', 'S2-249013014', 'S2-197070651', 'S3-478195123', 'S3-384364074', 'S2-790675320', 'S2-479876582', 'S3-878454467', 'S2-153058913', 'S2-24659151', 'S3-679606215', 'S2-478959098', 'S2-553508714', 'S2-625774905', 'S3-728090388', 'S3-928796641', 'S3-449308785', 'S2-755677256', 'S3-187831601', 'S3-641489370', 'S3-476250621', 'S2-660036492', 'S3-804600254', 'S3-274817120', 'S3-312496301', 'S2-648035184', 'S3-588502663', 'S2-383871912', 'S3-74481402', 'S3-576451439']

34

In [97]:
s2_ids = []
s3_ids = []

for entity_id in all_matched_ids:

    if entity_id.startswith("S2-"):
        s2_ids.append(entity_id)

    elif entity_id.startswith("S3-"):
        s3_ids.append(entity_id)

In [98]:
s2_matches = source2[source2["entity_id"].isin(s2_ids)] #find correspoding rows in s2 and s3
s3_matches = source3[source3["entity_id"].isin(s3_ids)]

In [99]:
s2_matches

,entity_id,business_name,business_address,country
191919,S2-648035184,Hendricks and Flowers Inc,"CT, SLEEPY HOLLOW DRIVE, DANBURY",US
223808,S2-755677256,Lumay Boral Inc.,"1056-1060 BELDEN AVE, PO BOX 8807, AKRON, OH",US
385243,S2-625774905,PAYNE-ENRTPRMISES,"3315 FREMONT SAINT, PEORIA, IL",US
488130,S2-383871912,होटल एंटरप्राइजेज लिमिटेड,"WZ-187C SHOP NO.13, DELHI, WEST DELHI, Delhi",India
731099,S2-478959098,Payne Énterprises,"3315 FREMONT ST, PEORIA, IL",US
809231,S2-660036492,रेड वेंचर्स प्राइवेट लिमिटेड,"G-1, BANIPARK, JAIPUR, Rajasthan",India
1376739,S2-681193310,Maure Wilblims Colombier Inc,NaN,US
1776076,S2-553508714,Payne Enterpires,"3315 FREMONT ST, PEORIA, IL",US
1886844,S2-197070651,Raj Investments LLP,"6(29), C.I.T. COLONY, 2ND MAIN ROAD MYLAPORE, ...",India
1901972,S2-479876582,Dahlia Power Reliable Scientific,"45ND TERRACE, null, KANSAS CITY, MO",US
2003754,S2-743505751,Maure Williams Colombier,NaN,US
2630198,S2-153058913,एसएस फूड प्राइवेट लिमिटेड,"AF-0684, NANDGRAM NEAR MOTHER INDIA PUBLIC SCH...",India
3579917,S2-790675320,Dahlia Power Reliable,"KANSAS CITY, MO, 630 45ND TERRACE, null",US
4130950,S2-249013014,ராஜ் இன்வெஸ்ட்மெண்ட்ஸ் எல்எல்பி,"6(29), C.I.T. COLONY, 2ND MAIN ROAD MYLAPORE, ...",India
5014138,S2-24659151,एसएस फूड प्राइवेट लिमिटेड,"AF-0684, Uttar Pradesh, GHAZIABAD, 9487203",India

In [100]:
s1_ids = positive_examples["source1_entity_id"].tolist()

In [101]:
s1_ids

['S1-965667',
 'S1-55344266',
 'S1-343815751',
 'S1-656753428',
 'S1-102811957',
 'S1-18727616',
 'S1-318373630',
 'S1-86989137',
 'S1-29845983',
 'S1-789009573']

In [102]:
s1_matches = source1[source1["entity_id"].isin(s1_ids)]
s1_matches

,entity_id,business_name,business_address,country
539414,S1-102811957,Payne Enterprises,"3315 Fremont Street, Peoria, IL",US
547338,S1-343815751,Dahlia Power Reliable Scientific LLC,"630 45th Terrace, Kansas City, MO",US
603899,S1-318373630,Red Ventures Private Limited,"Rajasthan, Jaipur, Banipark, Gokul Apartment, ...",India
841520,S1-86989137,Laxmi Golden Investments Private Limited,"New Bridge Business Centre'S 11Th Floor, N1 Bl...",India
1072115,S1-656753428,Ss Food Private Limited,"Af-684, Nandgram Near Mother India Public Scho...",India
1232493,S1-29845983,Hendricks and Flowers Inc,"33 Sleepy Hollow Drive, Danbury, CT",US
1265942,S1-789009573,Hotel Enterprises Limited,"Wz-187C Shop No.13, 14 Kh. No.47 S/F. Vikaspur...",India
1286323,S1-965667,Maure Williams Colombier Inc,"85 Wayne Avenue, Ticonderoga, NY",US
1898165,S1-55344266,Raj Investments LLP,"6(29), C.I.T. Colony, 2Nd Main Road Mylapore, ...",India
2117972,S1-18727616,Lumay Boral,"1056 Belden Avenue, Akron, OH",US

In [103]:
print(s1_matches.shape)
print(s2_matches.shape)
print(s3_matches.shape)

(10, 4)
(15, 4)
(19, 4)

In [ ]:
positive_pairs = []
for _, row in positive_examples.iterrows():

    s1_id = row["source1_entity_id"]
    matched_ids = row["matched_entity_ids"].split(",")

    for matched_id in matched_ids:

        positive_pairs.append(
            {"source1_entity_id": s1_id,"matched_entity_id": matched_id}
        )

In [105]:
positive_pairs

[{'source1_entity_id': 'S1-965667', 'matched_entity_id': 'S2-681193310'},
 {'source1_entity_id': 'S1-965667', 'matched_entity_id': 'S2-743505751'},
 {'source1_entity_id': 'S1-965667', 'matched_entity_id': 'S3-775321672'},
 {'source1_entity_id': 'S1-965667', 'matched_entity_id': 'S3-11291185'},
 {'source1_entity_id': 'S1-965667', 'matched_entity_id': 'S3-860443364'},
 {'source1_entity_id': 'S1-55344266', 'matched_entity_id': 'S2-249013014'},
 {'source1_entity_id': 'S1-55344266', 'matched_entity_id': 'S2-197070651'},
 {'source1_entity_id': 'S1-55344266', 'matched_entity_id': 'S3-478195123'},
 {'source1_entity_id': 'S1-55344266', 'matched_entity_id': 'S3-384364074'},
 {'source1_entity_id': 'S1-343815751', 'matched_entity_id': 'S2-790675320'},
 {'source1_entity_id': 'S1-343815751', 'matched_entity_id': 'S2-479876582'},
 {'source1_entity_id': 'S1-343815751', 'matched_entity_id': 'S3-878454467'},
 {'source1_entity_id': 'S1-656753428', 'matched_entity_id': 'S2-153058913'},
 {'source1_entity_id': 'S1-656753428', 'matched_entity_id': 'S2-24659151'},
 {'source1_entity_id': 'S1-656753428', 'matched_entity_id': 'S3-679606215'},
 {'source1_entity_id': 'S1-102811957', 'matched_entity_id': 'S2-478959098'},
 {'source1_entity_id': 'S1-102811957', 'matched_entity_id': 'S2-553508714'},
 {'source1_entity_id': 'S1-102811957', 'matched_entity_id': 'S2-625774905'},
 {'source1_entity_id': 'S1-102811957', 'matched_entity_id': 'S3-728090388'},
 {'source1_entity_id': 'S1-102811957', 'matched_entity_id': 'S3-928796641'},
 {'source1_entity_id': 'S1-102811957', 'matched_entity_id': 'S3-449308785'},
 {'source1_entity_id': 'S1-18727616', 'matched_entity_id': 'S2-755677256'},
 {'source1_entity_id': 'S1-18727616', 'matched_entity_id': 'S3-187831601'},
 {'source1_entity_id': 'S1-18727616', 'matched_entity_id': 'S3-641489370'},
 {'source1_entity_id': 'S1-18727616', 'matched_entity_id': 'S3-476250621'},
 {'source1_entity_id': 'S1-318373630', 'matched_entity_id': 'S2-660036492'},
 {'source1_entity_id': 'S1-318373630', 'matched_entity_id': 'S3-804600254'},
 {'source1_entity_id': 'S1-86989137', 'matched_entity_id': 'S3-274817120'},
 {'source1_entity_id': 'S1-86989137', 'matched_entity_id': 'S3-312496301'},
 {'source1_entity_id': 'S1-29845983', 'matched_entity_id': 'S2-648035184'},
 {'source1_entity_id': 'S1-29845983', 'matched_entity_id': 'S3-588502663'},
 {'source1_entity_id': 'S1-789009573', 'matched_entity_id': 'S2-383871912'},
 {'source1_entity_id': 'S1-789009573', 'matched_entity_id': 'S3-74481402'},
 {'source1_entity_id': 'S1-789009573', 'matched_entity_id': 'S3-576451439'}]

In [106]:
positive_pairs = pd.DataFrame(positive_pairs)

In [107]:
positive_pairs.head()

  source1_entity_id matched_entity_id
0         S1-965667      S2-681193310
1         S1-965667      S2-743505751
2         S1-965667      S3-775321672
3         S1-965667       S3-11291185
4         S1-965667      S3-860443364

In [108]:
source23 = pd.concat([source2,source3],ignore_index=True)

In [109]:
positive_pairs = positive_pairs.merge(source23,
    left_on="matched_entity_id",
    right_on="entity_id",
    how="left",
    suffixes=(
        "_s1",
        "_matched"
    )
)

In [ ]:
positive_pairs.head(10)
#from here we can see for S1 Maure Wilblims Colomiebr Inc and how is it matching on the basis of names and not the address
# see indexes 0 and 1 we dont' have adress but we have names and similary in index 2 we can comapre it with the address

,source1_entity_id,matched_entity_id,entity_id,business_name,business_address,country
0,S1-965667,S2-681193310,S2-681193310,Maure Wilblims Colombier Inc,NaN,US
1,S1-965667,S2-743505751,S2-743505751,Maure Williams Colombier,NaN,US
2,S1-965667,S3-775321672,S3-775321672,Dréxkor,"85 Wanye Avenue, Ticonderoga Townshiip, New York",US
3,S1-965667,S3-11291185,S3-11291185,maurewilliamscolombier.com,"Wayne Ave, Ticonderoga Townshiip, New York",US
4,S1-965667,S3-860443364,S3-860443364,Maure Williams Inc Center,NaN,US
5,S1-55344266,S2-249013014,S2-249013014,ராஜ் இன்வெஸ்ட்மெண்ட்ஸ் எல்எல்பி,"6(29), C.I.T. COLONY, 2ND MAIN ROAD MYLAPORE, ...",India
6,S1-55344266,S2-197070651,S2-197070651,Raj Investments LLP,"6(29), C.I.T. COLONY, 2ND MAIN ROAD MYLAPORE, ...",India
7,S1-55344266,S3-478195123,S3-478195123,Raj Investments எல்எல்பி,"6(29), C.i.t. Colony, 2Nd Main Road Mylapore, ...",India
8,S1-55344266,S3-384364074,S3-384364074,ராஜ் இன்வெஸ்ட்மெண்ட்ஸ் எல்எல்பி,"6(29), C.i.t. Colony, 2Nd Main Road Mylapore, ...",India
9,S1-343815751,S2-790675320,S2-790675320,Dahlia Power Reliable,"KANSAS CITY, MO, 630 45ND TERRACE, null",US

In [113]:
s1_info = source1[
    [
        "entity_id",
        "business_name",
        "business_address",
        "country"
    ]
]

In [114]:
s1_info = s1_info.rename(
    columns={
        "entity_id": "source1_entity_id",
        "business_name": "business_name_s1",
        "business_address": "business_address_s1",
        "country": "country_s1"
    }
)

In [ ]:
positive_pairs = positive_pairs.merge(
    s1_info,
    on="source1_entity_id",
    how="left"
)

In [117]:
positive_pairs.head()

,source1_entity_id,matched_entity_id,entity_id,business_name,business_address,country,business_name_s1,business_address_s1,country_s1
0,S1-965667,S2-681193310,S2-681193310,Maure Wilblims Colombier Inc,NaN,US,Maure Williams Colombier Inc,"85 Wayne Avenue, Ticonderoga, NY",US
1,S1-965667,S2-743505751,S2-743505751,Maure Williams Colombier,NaN,US,Maure Williams Colombier Inc,"85 Wayne Avenue, Ticonderoga, NY",US
2,S1-965667,S3-775321672,S3-775321672,Dréxkor,"85 Wanye Avenue, Ticonderoga Townshiip, New York",US,Maure Williams Colombier Inc,"85 Wayne Avenue, Ticonderoga, NY",US
3,S1-965667,S3-11291185,S3-11291185,maurewilliamscolombier.com,"Wayne Ave, Ticonderoga Townshiip, New York",US,Maure Williams Colombier Inc,"85 Wayne Avenue, Ticonderoga, NY",US
4,S1-965667,S3-860443364,S3-860443364,Maure Williams Inc Center,NaN,US,Maure Williams Colombier Inc,"85 Wayne Avenue, Ticonderoga, NY",US

In [118]:
positive_pairs = positive_pairs.rename(
    columns={
        "business_name": "business_name_matched",
        "business_address": "business_address_matched",
        "country": "country_matched"
    }
)

In [119]:
positive_pairs.head()

,source1_entity_id,matched_entity_id,entity_id,business_name_matched,business_address_matched,country_matched,business_name_s1,business_address_s1,country_s1
0,S1-965667,S2-681193310,S2-681193310,Maure Wilblims Colombier Inc,NaN,US,Maure Williams Colombier Inc,"85 Wayne Avenue, Ticonderoga, NY",US
1,S1-965667,S2-743505751,S2-743505751,Maure Williams Colombier,NaN,US,Maure Williams Colombier Inc,"85 Wayne Avenue, Ticonderoga, NY",US
2,S1-965667,S3-775321672,S3-775321672,Dréxkor,"85 Wanye Avenue, Ticonderoga Townshiip, New York",US,Maure Williams Colombier Inc,"85 Wayne Avenue, Ticonderoga, NY",US
3,S1-965667,S3-11291185,S3-11291185,maurewilliamscolombier.com,"Wayne Ave, Ticonderoga Townshiip, New York",US,Maure Williams Colombier Inc,"85 Wayne Avenue, Ticonderoga, NY",US
4,S1-965667,S3-860443364,S3-860443364,Maure Williams Inc Center,NaN,US,Maure Williams Colombier Inc,"85 Wayne Avenue, Ticonderoga, NY",US

In [121]:
from rapidfuzz.fuzz import ratio

In [ ]:
name_1 = positive_pairs.loc[0,"business_name_s1"]
name_2 = positive_pairs.loc[0,"business_name_matched"]

In [123]:
print(name_1)
print(name_2)

Maure Williams Colombier Inc
Maure Wilblims Colombier Inc

In [124]:
name_similarity = ratio(name_1,name_2)
print(name_similarity)

96.42857142857143

In [126]:
name_similarities = []

for _, row in positive_pairs.head(10).iterrows():
    name_1 = row["business_name_s1"]
    name_2 = row["business_name_matched"]

    similarity = ratio(name_1,name_2)
    name_similarities.append(similarity)

print(name_similarities)

[96.42857142857143, 92.3076923076923, 17.14285714285714, 74.07407407407408, 67.9245283018868, 7.9999999999999964, 100.0, 74.4186046511628, 7.9999999999999964, 73.6842105263158]

In [127]:
positive_pairs.head(10)

,source1_entity_id,matched_entity_id,entity_id,business_name_matched,business_address_matched,country_matched,business_name_s1,business_address_s1,country_s1
0,S1-965667,S2-681193310,S2-681193310,Maure Wilblims Colombier Inc,NaN,US,Maure Williams Colombier Inc,"85 Wayne Avenue, Ticonderoga, NY",US
1,S1-965667,S2-743505751,S2-743505751,Maure Williams Colombier,NaN,US,Maure Williams Colombier Inc,"85 Wayne Avenue, Ticonderoga, NY",US
2,S1-965667,S3-775321672,S3-775321672,Dréxkor,"85 Wanye Avenue, Ticonderoga Townshiip, New York",US,Maure Williams Colombier Inc,"85 Wayne Avenue, Ticonderoga, NY",US
3,S1-965667,S3-11291185,S3-11291185,maurewilliamscolombier.com,"Wayne Ave, Ticonderoga Townshiip, New York",US,Maure Williams Colombier Inc,"85 Wayne Avenue, Ticonderoga, NY",US
4,S1-965667,S3-860443364,S3-860443364,Maure Williams Inc Center,NaN,US,Maure Williams Colombier Inc,"85 Wayne Avenue, Ticonderoga, NY",US
5,S1-55344266,S2-249013014,S2-249013014,ராஜ் இன்வெஸ்ட்மெண்ட்ஸ் எல்எல்பி,"6(29), C.I.T. COLONY, 2ND MAIN ROAD MYLAPORE, ...",India,Raj Investments LLP,"6(29), C.I.T. Colony, 2Nd Main Road Mylapore, ...",India
6,S1-55344266,S2-197070651,S2-197070651,Raj Investments LLP,"6(29), C.I.T. COLONY, 2ND MAIN ROAD MYLAPORE, ...",India,Raj Investments LLP,"6(29), C.I.T. Colony, 2Nd Main Road Mylapore, ...",India
7,S1-55344266,S3-478195123,S3-478195123,Raj Investments எல்எல்பி,"6(29), C.i.t. Colony, 2Nd Main Road Mylapore, ...",India,Raj Investments LLP,"6(29), C.I.T. Colony, 2Nd Main Road Mylapore, ...",India
8,S1-55344266,S3-384364074,S3-384364074,ராஜ் இன்வெஸ்ட்மெண்ட்ஸ் எல்எல்பி,"6(29), C.i.t. Colony, 2Nd Main Road Mylapore, ...",India,Raj Investments LLP,"6(29), C.I.T. Colony, 2Nd Main Road Mylapore, ...",India
9,S1-343815751,S2-790675320,S2-790675320,Dahlia Power Reliable,"KANSAS CITY, MO, 630 45ND TERRACE, null",US,Dahlia Power Reliable Scientific LLC,"630 45th Terrace, Kansas City, MO",US

In [130]:
address_pairs = positive_pairs[positive_pairs["business_address_matched"].notna()]
address_pairs.head()

,source1_entity_id,matched_entity_id,entity_id,business_name_matched,business_address_matched,country_matched,business_name_s1,business_address_s1,country_s1
2,S1-965667,S3-775321672,S3-775321672,Dréxkor,"85 Wanye Avenue, Ticonderoga Townshiip, New York",US,Maure Williams Colombier Inc,"85 Wayne Avenue, Ticonderoga, NY",US
3,S1-965667,S3-11291185,S3-11291185,maurewilliamscolombier.com,"Wayne Ave, Ticonderoga Townshiip, New York",US,Maure Williams Colombier Inc,"85 Wayne Avenue, Ticonderoga, NY",US
5,S1-55344266,S2-249013014,S2-249013014,ராஜ் இன்வெஸ்ட்மெண்ட்ஸ் எல்எல்பி,"6(29), C.I.T. COLONY, 2ND MAIN ROAD MYLAPORE, ...",India,Raj Investments LLP,"6(29), C.I.T. Colony, 2Nd Main Road Mylapore, ...",India
6,S1-55344266,S2-197070651,S2-197070651,Raj Investments LLP,"6(29), C.I.T. COLONY, 2ND MAIN ROAD MYLAPORE, ...",India,Raj Investments LLP,"6(29), C.I.T. Colony, 2Nd Main Road Mylapore, ...",India
7,S1-55344266,S3-478195123,S3-478195123,Raj Investments எல்எல்பி,"6(29), C.i.t. Colony, 2Nd Main Road Mylapore, ...",India,Raj Investments LLP,"6(29), C.I.T. Colony, 2Nd Main Road Mylapore, ...",India

In [ ]:
address_pairs[["business_address_s1","business_address_matched"]].head(5)

,business_address_s1,business_address_matched
2,"85 Wayne Avenue, Ticonderoga, NY","85 Wanye Avenue, Ticonderoga Townshiip, New York"
3,"85 Wayne Avenue, Ticonderoga, NY","Wayne Ave, Ticonderoga Townshiip, New York"
5,"6(29), C.I.T. Colony, 2Nd Main Road Mylapore, ...","6(29), C.I.T. COLONY, 2ND MAIN ROAD MYLAPORE, ..."
6,"6(29), C.I.T. Colony, 2Nd Main Road Mylapore, ...","6(29), C.I.T. COLONY, 2ND MAIN ROAD MYLAPORE, ..."
7,"6(29), C.I.T. Colony, 2Nd Main Road Mylapore, ...","6(29), C.i.t. Colony, 2Nd Main Road Mylapore, ..."

In [ ]:
address_1 = address_pairs.iloc[0]["business_address_s1"]
address_2 = address_pairs.iloc[0]["business_address_matched"]

print(address_1)
print(address_2)

85 Wayne Avenue, Ticonderoga, NY
85 Wanye Avenue, Ticonderoga Townshiip, New York

In [136]:
address_similarity = ratio(address_1,address_2)
print(address_similarity)

77.5

In [ ]:
country_1 = positive_pairs.loc[0,"country_s1"]
country_2 = positive_pairs.loc[0,"country_matched"]

country_same = int(country_1 == country_2)
print(country_same)

#ok so we basically need to distinguish between the two using similarity on basis of name address country and other features

1

In [138]:
address_1 = positive_pairs.loc[0,"business_address_s1"]
address_2 = positive_pairs.loc[0,"business_address_matched"]

address_1_missing = int(pd.isna(address_1))
address_2_missing = int(pd.isna(address_2))


print(address_1_missing)
print(address_2_missing)

0
1

In [141]:
pair_features = []
for _, row in positive_pairs.head(10).iterrows():

    name_1 = row["business_name_s1"]
    name_2 = row["business_name_matched"]

    address_1 = row["business_address_s1"]
    address_2 = row["business_address_matched"]

    country_1 = row["country_s1"]
    country_2 = row["country_matched"]

    name_similarity = ratio(name_1,name_2)

    if pd.isna(address_1) or pd.isna(address_2):
        address_similarity = None

    else:
        address_similarity = ratio(address_1,address_2)

    country_same = int(
        country_1 == country_2
    )

    address_1_missing = int(
        pd.isna(address_1)
    )

    address_2_missing = int(
        pd.isna(address_2)
    )

    pair_features.append(
        {
            "source1_entity_id": row["source1_entity_id"],
            "matched_entity_id": row["matched_entity_id"],
            "name_similarity": name_similarity,
            "address_similarity": address_similarity,
            "country_same": country_same,
            "address_1_missing": address_1_missing,
            "address_2_missing": address_2_missing
        }
    )

In [143]:
pair_features

[{'source1_entity_id': 'S1-965667',
  'matched_entity_id': 'S2-681193310',
  'name_similarity': 96.42857142857143,
  'address_similarity': None,
  'country_same': 1,
  'address_1_missing': 0,
  'address_2_missing': 1},
 {'source1_entity_id': 'S1-965667',
  'matched_entity_id': 'S2-743505751',
  'name_similarity': 92.3076923076923,
  'address_similarity': None,
  'country_same': 1,
  'address_1_missing': 0,
  'address_2_missing': 1},
 {'source1_entity_id': 'S1-965667',
  'matched_entity_id': 'S3-775321672',
  'name_similarity': 17.14285714285714,
  'address_similarity': 77.5,
  'country_same': 1,
  'address_1_missing': 0,
  'address_2_missing': 0},
 {'source1_entity_id': 'S1-965667',
  'matched_entity_id': 'S3-11291185',
  'name_similarity': 74.07407407407408,
  'address_similarity': 70.27027027027026,
  'country_same': 1,
  'address_1_missing': 0,
  'address_2_missing': 0},
 {'source1_entity_id': 'S1-965667',
  'matched_entity_id': 'S3-860443364',
  'name_similarity': 67.9245283018868,
  'address_similarity': None,
  'country_same': 1,
  'address_1_missing': 0,
  'address_2_missing': 1},
 {'source1_entity_id': 'S1-55344266',
  'matched_entity_id': 'S2-249013014',
  'name_similarity': 7.9999999999999964,
  'address_similarity': 61.53846153846154,
  'country_same': 1,
  'address_1_missing': 0,
  'address_2_missing': 0},
 {'source1_entity_id': 'S1-55344266',
  'matched_entity_id': 'S2-197070651',
  'name_similarity': 100.0,
  'address_similarity': 61.53846153846154,
  'country_same': 1,
  'address_1_missing': 0,
  'address_2_missing': 0},
 {'source1_entity_id': 'S1-55344266',
  'matched_entity_id': 'S3-478195123',
  'name_similarity': 74.4186046511628,
  'address_similarity': 90.1639344262295,
  'country_same': 1,
  'address_1_missing': 0,
  'address_2_missing': 0},
 {'source1_entity_id': 'S1-55344266',
  'matched_entity_id': 'S3-384364074',
  'name_similarity': 7.9999999999999964,
  'address_similarity': 82.17054263565892,
  'country_same': 1,
  'address_1_missing': 0,
  'address_2_missing': 0},
 {'source1_entity_id': 'S1-343815751',
  'matched_entity_id': 'S2-790675320',
  'name_similarity': 73.6842105263158,
  'address_similarity': 30.555555555555557,
  'country_same': 1,
  'address_1_missing': 0,
  'address_2_missing': 0}]

In [ ]:
pair_features = pd.DataFrame(pair_features)
pair_features.head()
#now get an idea how can we use similarity scores to predict which one is which
#now we have tested this for positive paris and we need to check this for negative pairs as well 
#means the paris that don't match

,source1_entity_id,matched_entity_id,name_similarity,address_similarity,country_same,address_1_missing,address_2_missing
0,S1-965667,S2-681193310,96.428571,NaN,1,0,1
1,S1-965667,S2-743505751,92.307692,NaN,1,0,1
2,S1-965667,S3-775321672,17.142857,77.50000,1,0,0
3,S1-965667,S3-11291185,74.074074,70.27027,1,0,0
4,S1-965667,S3-860443364,67.924528,NaN,1,0,1

In [ ]:
s1_id = "S1-965667"

In [150]:
positive_pairs[positive_pairs["source1_entity_id"] == s1_id]["matched_entity_id"]

31    S2-383871912
32     S3-74481402
33    S3-576451439
Name: matched_entity_id, dtype: str

In [151]:
negative_record = source23[(source23["country"] == "US")].iloc[0]

In [ ]:
negative_record[
        [
            "entity_id",
            "business_name",
            "business_address",
            "country"
        ]
    ]

#OK from the ouput we can se ethe id S2-764573417 is not in the mathcing of the s1_id we took

entity_id                           S2-764573417
business_name       -- Holloway Peak Inc Seafood
business_address       105 ELM ST, MORGANTON, NC
country                                       US
Name: 1, dtype: str

In [154]:
s1_id = "S1-965667"

In [156]:
positive_pairs.head()

,source1_entity_id,matched_entity_id,entity_id,business_name_matched,business_address_matched,country_matched,business_name_s1,business_address_s1,country_s1
0,S1-965667,S2-681193310,S2-681193310,Maure Wilblims Colombier Inc,NaN,US,Maure Williams Colombier Inc,"85 Wayne Avenue, Ticonderoga, NY",US
1,S1-965667,S2-743505751,S2-743505751,Maure Williams Colombier,NaN,US,Maure Williams Colombier Inc,"85 Wayne Avenue, Ticonderoga, NY",US
2,S1-965667,S3-775321672,S3-775321672,Dréxkor,"85 Wanye Avenue, Ticonderoga Townshiip, New York",US,Maure Williams Colombier Inc,"85 Wayne Avenue, Ticonderoga, NY",US
3,S1-965667,S3-11291185,S3-11291185,maurewilliamscolombier.com,"Wayne Ave, Ticonderoga Townshiip, New York",US,Maure Williams Colombier Inc,"85 Wayne Avenue, Ticonderoga, NY",US
4,S1-965667,S3-860443364,S3-860443364,Maure Williams Inc Center,NaN,US,Maure Williams Colombier Inc,"85 Wayne Avenue, Ticonderoga, NY",US

In [155]:
true_matches = positive_pairs[
    positive_pairs["source1_entity_id"] == s1_id
]

print(
    true_matches["matched_entity_id"]
)

0    S2-681193310
1    S2-743505751
2    S3-775321672
3     S3-11291185
4    S3-860443364
Name: matched_entity_id, dtype: str

In [158]:
negative_record = source23[source23["country"] == "US"].iloc[0]
print(negative_record)

entity_id                           S2-764573417
business_name       -- Holloway Peak Inc Seafood
business_address       105 ELM ST, MORGANTON, NC
country                                       US
Name: 1, dtype: str

In [159]:
negative_id = negative_record["entity_id"]

print(
    negative_id in true_matches["matched_entity_id"].values
)

False

In [160]:
s1_record = source1[source1["entity_id"] == s1_id].iloc[0]
print(s1_record)

entity_id                                  S1-965667
business_name           Maure Williams Colombier Inc
business_address    85 Wayne Avenue, Ticonderoga, NY
country                                           US
Name: 1286323, dtype: str

In [161]:
pair_features = []

for _, row in positive_pairs.head(10).iterrows():

    name_1 = row["business_name_s1"]
    name_2 = row["business_name_matched"]

    address_1 = row["business_address_s1"]
    address_2 = row["business_address_matched"]

    country_1 = row["country_s1"]
    country_2 = row["country_matched"]

    name_similarity = ratio(name_1,name_2)

    if pd.isna(address_1) or pd.isna(address_2):
        address_similarity = None


    else:
        address_similarity = ratio(address_1,address_2)


    country_same = int(country_1 == country_2)

    address_1_missing = int(pd.isna(address_1))

    address_2_missing = int(pd.isna(address_2))

    pair_features.append(
        {
            "source1_entity_id": row["source1_entity_id"],
            "matched_entity_id": row["matched_entity_id"],
            "label": 1,
            "name_similarity": name_similarity,
            "address_similarity": address_similarity,
            "country_same": country_same,
            "address_1_missing": address_1_missing,
            "address_2_missing": address_2_missing
        }
    )

positive_features = pd.DataFrame(pair_features)
positive_features

,source1_entity_id,matched_entity_id,label,name_similarity,address_similarity,country_same,address_1_missing,address_2_missing
0,S1-965667,S2-681193310,1,96.428571,NaN,1,0,1
1,S1-965667,S2-743505751,1,92.307692,NaN,1,0,1
2,S1-965667,S3-775321672,1,17.142857,77.500000,1,0,0
3,S1-965667,S3-11291185,1,74.074074,70.270270,1,0,0
4,S1-965667,S3-860443364,1,67.924528,NaN,1,0,1
5,S1-55344266,S2-249013014,1,8.000000,61.538462,1,0,0
6,S1-55344266,S2-197070651,1,100.000000,61.538462,1,0,0
7,S1-55344266,S3-478195123,1,74.418605,90.163934,1,0,0
8,S1-55344266,S3-384364074,1,8.000000,82.170543,1,0,0
9,S1-343815751,S2-790675320,1,73.684211,30.555556,1,0,0

In [162]:
negative_pairs = []

for _, s1_row in source1.head(10).iterrows():
    s1_id = s1_row["entity_id"]

    true_matches = ground_truth[ground_truth["source1_entity_id"] == s1_id]["matched_entity_ids"].iloc[0]

    true_matches = (
        []
        if pd.isna(true_matches)
        else true_matches.split(",")
    )

    for _, candidate_row in source23.iterrows():
        candidate_id = candidate_row["entity_id"]

        if candidate_id not in true_matches:

            negative_pairs.append(
                {
                    "source1_entity_id": s1_id,
                    "matched_entity_id": candidate_id,
                    "business_name_s1": s1_row["business_name"],
                    "business_name_matched": candidate_row["business_name"],
                    "business_address_s1": s1_row["business_address"],
                    "business_address_matched": candidate_row["business_address"],
                    "country_s1": s1_row["country"],
                    "country_matched": candidate_row["country"]
                }
            )

            break

    if len(negative_pairs) >= 10:
        break

In [166]:
negative_pairs = pd.DataFrame(negative_pairs)
negative_pairs.head()

,source1_entity_id,matched_entity_id,business_name_s1,business_name_matched,business_address_s1,business_address_matched,country_s1,country_matched
0,S1-925783039,S2-166376419,Orelee's Barbershop,राम मार्केटिंग प्राइवेट लिमिटेड,"1795 Westchester Drive, High Point, NC","KH NO. -570/13, NEW DELHI, WEST DELHI, Delhi",US,India
1,S1-773889195,S2-166376419,Prime Money,राम मार्केटिंग प्राइवेट लिमिटेड,"17560 Ellis Road, Tahlequah, OK","KH NO. -570/13, NEW DELHI, WEST DELHI, Delhi",US,India
2,S1-377745466,S2-166376419,B+ Retail Inc,राम मार्केटिंग प्राइवेट लिमिटेड,"1712 Montebello Avenue, Phoenix, AZ","KH NO. -570/13, NEW DELHI, WEST DELHI, Delhi",US,India
3,S1-133037285,S2-166376419,Christ Chapel,राम मार्केटिंग प्राइवेट लिमिटेड,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD","KH NO. -570/13, NEW DELHI, WEST DELHI, Delhi",US,India
4,S1-755362802,S2-166376419,Prabhav Business Center,राम मार्केटिंग प्राइवेट लिमिटेड,"797, Lake Town Block A, Kolkata, Howrah, West ...","KH NO. -570/13, NEW DELHI, WEST DELHI, Delhi",India,India

In [167]:
negative_features = []

for _, row in pd.DataFrame(negative_pairs).iterrows():
    name_1 = row["business_name_s1"]
    name_2 = row["business_name_matched"]

    address_1 = row["business_address_s1"]
    address_2 = row["business_address_matched"]

    country_1 = row["country_s1"]
    country_2 = row["country_matched"]

    name_similarity = ratio(name_1,name_2)

    if pd.isna(address_1) or pd.isna(address_2):
        address_similarity = None

    else:
        address_similarity = ratio(address_1,address_2)


    country_same = int(country_1 == country_2)
    address_1_missing = int(pd.isna(address_1))
    address_2_missing = int(pd.isna(address_2))

    negative_features.append(
        {
            "source1_entity_id": row["source1_entity_id"],
            "matched_entity_id": row["matched_entity_id"],
            "label": 0,
            "name_similarity": name_similarity,
            "address_similarity": address_similarity,
            "country_same": country_same,
            "address_1_missing": address_1_missing,
            "address_2_missing": address_2_missing
        }
    )

negative_features = pd.DataFrame(
    negative_features
)

negative_features

,source1_entity_id,matched_entity_id,label,name_similarity,address_similarity,country_same,address_1_missing,address_2_missing
0,S1-925783039,S2-166376419,0,4.000000,24.390244,0,0,0
1,S1-773889195,S2-166376419,0,4.761905,26.666667,0,0,0
2,S1-377745466,S2-166376419,0,9.090909,20.253165,0,0,0
3,S1-133037285,S2-166376419,0,4.545455,27.956989,0,0,0
4,S1-755362802,S2-166376419,0,7.407407,25.000000,1,0,0
5,S1-851869949,S2-166376419,0,10.526316,20.779221,0,0,0
6,S1-785847572,S2-166376419,0,8.450704,19.393939,1,0,0
7,S1-27541239,S2-166376419,0,8.333333,22.727273,0,0,0
8,S1-629417405,S2-166376419,0,8.333333,22.222222,0,0,0
9,S1-22305073,S2-166376419,0,7.017544,19.417476,0,0,0

In [170]:
all_features = pd.concat(
    [
        positive_features,
        negative_features
    ],
    ignore_index=True
)

all_features.head(10)

,source1_entity_id,matched_entity_id,label,name_similarity,address_similarity,country_same,address_1_missing,address_2_missing
0,S1-965667,S2-681193310,1,96.428571,NaN,1,0,1
1,S1-965667,S2-743505751,1,92.307692,NaN,1,0,1
2,S1-965667,S3-775321672,1,17.142857,77.500000,1,0,0
3,S1-965667,S3-11291185,1,74.074074,70.270270,1,0,0
4,S1-965667,S3-860443364,1,67.924528,NaN,1,0,1
5,S1-55344266,S2-249013014,1,8.000000,61.538462,1,0,0
6,S1-55344266,S2-197070651,1,100.000000,61.538462,1,0,0
7,S1-55344266,S3-478195123,1,74.418605,90.163934,1,0,0
8,S1-55344266,S3-384364074,1,8.000000,82.170543,1,0,0
9,S1-343815751,S2-790675320,1,73.684211,30.555556,1,0,0

In [ ]:
all_features.tail(10)

,source1_entity_id,matched_entity_id,label,name_similarity,address_similarity,country_same,address_1_missing,address_2_missing
10,S1-925783039,S2-166376419,0,4.000000,24.390244,0,0,0
11,S1-773889195,S2-166376419,0,4.761905,26.666667,0,0,0
12,S1-377745466,S2-166376419,0,9.090909,20.253165,0,0,0
13,S1-133037285,S2-166376419,0,4.545455,27.956989,0,0,0
14,S1-755362802,S2-166376419,0,7.407407,25.000000,1,0,0
15,S1-851869949,S2-166376419,0,10.526316,20.779221,0,0,0
16,S1-785847572,S2-166376419,0,8.450704,19.393939,1,0,0
17,S1-27541239,S2-166376419,0,8.333333,22.727273,0,0,0
18,S1-629417405,S2-166376419,0,8.333333,22.222222,0,0,0
19,S1-22305073,S2-166376419,0,7.017544,19.417476,0,0,0